"""Vinacount public package API."""

from vinacount.canonical_source_selection import (
    CanonicalSourceSelectionRecord,
    CanonicalSourceSelectionResult,
    select_canonical_source_from_classifications,
)
from vinacount.filing_package import (
    CanonicalSourceSelection,
    CanonicalSourceSelectionError,
    FilingPackage,
    LocalSourceDocument,
    SourceDocument,
    ingest_local_filing_package,
    select_canonical_source,
    validate_filing_package,
)
from vinacount.final_report import (
    build_final_report,
    render_final_report_markdown,
    validate_final_report,
    write_final_report,
)
from vinacount.ocr_adapter import (
    NanonetsOcr3DocstrangeAdapter,
    NanonetsOcr3DocstrangeConfig,
)
from vinacount.raw_extraction_artifact import (
    RawExtractionArtifact,
    validate_raw_extraction_artifact,
)
from vinacount.raw_ocr_candidate_mapper import (
    MAPPER_VERSION,
    RawOcrCandidateMappingError,
    map_raw_ocr_artifact_to_extraction_candidates,
)
from vinacount.raw_ocr_llm_normalizer import (
    LLM_NORMALIZER_OUTPUT_SCHEMA_VERSION,
    LlmRawOcrNormalizerIdentity,
    RawOcrLlmNormalizationError,
    report_memory_cache_compatibility_for_llm_normalizer,
    validate_llm_normalizer_output,
)
from vinacount.report_memory_assembler import assemble_report_memory
from vinacount.report_artifact_cache import (
    PostgresReportArtifactCacheRepository,
    ReportMemoryArtifactCache,
    ReportMemoryCacheCompatibility,
    ReportMemoryCacheIdentity,
    ReportMemoryCacheRecord,
    SqliteReportArtifactCacheRepository,
)
from vinacount.report_model import (
    CompanyReportSet,
    RealExtractionQualityGateResult,
    ReportMemory,
    validate_company_report_set,
    validate_real_extraction_quality_gate,
    validate_report_memory,
)
from vinacount.runtime_contract import (
    AllowedAction,
    DEFAULT_REPORT_SYNTHESIS_MODEL_ID,
    FinalReportMetadata,
    REPORT_SYNTHESIS_MODEL_REGISTRY,
    ReportSynthesisModelConfig,
    RuntimeConfig,
    RuntimeErrorView,
    RuntimeFilingIntentView,
    RuntimeRunCreateRequest,
    RuntimeRunView,
    RuntimeStage,
    RuntimeWarning,
    SourceCandidate,
    SourceConfirmationSlot,
    SourceConfirmationView,
    assert_public_runtime_payload_safe,
    runtime_config_for_report_synthesis_model,
    runtime_contract_json_schemas,
    runtime_run_create_request_json_schema,
    runtime_run_view_json_schema,
    validate_filing_intent_error_response,
    validate_final_report_endpoint,
    validate_runtime_run_create_request,
    validate_runtime_run_view,
)
from vinacount.runtime_run_registry import (
    FilesystemArtifactBodyStore,
    InMemoryRuntimeRunStore,
    RuntimeRunRecord,
    RuntimeRunRegistry,
)
from vinacount.source_confirmation import build_source_confirmation_payload
from vinacount.source_document_classifier import (
    DeterministicSourceDocumentClassifier,
    SourceDocumentClassification,
    SourceDocumentClassificationResult,
    SourceDocumentClassifierInput,
    build_source_document_classifier_input,
    classify_filing_package_source_documents,
    validate_source_document_classification,
)
from vinacount.vietstock_fetched_source import (
    VietstockFetchedFilingPackageResult,
    VietstockFetchRecord,
    VietstockQuarterlyMetadataRow,
    VietstockQuarterlyMetadataScanResult,
    fetch_vietstock_filing_package,
    scan_vietstock_quarterly_metadata,
    scan_vietstock_quarterly_metadata_for_year,
)

__all__ = [
    "CanonicalSourceSelection",
    "CanonicalSourceSelectionError",
    "CanonicalSourceSelectionRecord",
    "CanonicalSourceSelectionResult",
    "CompanyReportSet",
    "DeterministicSourceDocumentClassifier",
    "FilingPackage",
    "LocalSourceDocument",
    "NanonetsOcr3DocstrangeAdapter",
    "NanonetsOcr3DocstrangeConfig",
    "RawExtractionArtifact",
    "RawOcrLlmNormalizationError",
    "RawOcrCandidateMappingError",
    "RealExtractionQualityGateResult",
    "ReportMemory",
    "ReportMemoryArtifactCache",
    "ReportMemoryCacheCompatibility",
    "ReportMemoryCacheIdentity",
    "ReportMemoryCacheRecord",
    "PostgresReportArtifactCacheRepository",
    "SourceDocument",
    "SourceDocumentClassification",
    "SourceDocumentClassificationResult",
    "SourceDocumentClassifierInput",
    "VietstockFetchedFilingPackageResult",
    "VietstockFetchRecord",
    "VietstockQuarterlyMetadataRow",
    "VietstockQuarterlyMetadataScanResult",
    "assemble_report_memory",
    "AllowedAction",
    "build_final_report",
    "build_source_confirmation_payload",
    "build_source_document_classifier_input",
    "classify_filing_package_source_documents",
    "DEFAULT_REPORT_SYNTHESIS_MODEL_ID",
    "fetch_vietstock_filing_package",
    "FinalReportMetadata",
    "FilesystemArtifactBodyStore",
    "ingest_local_filing_package",
    "InMemoryRuntimeRunStore",
    "LLM_NORMALIZER_OUTPUT_SCHEMA_VERSION",
    "LlmRawOcrNormalizerIdentity",
    "REPORT_SYNTHESIS_MODEL_REGISTRY",
    "ReportSynthesisModelConfig",
    "scan_vietstock_quarterly_metadata",
    "scan_vietstock_quarterly_metadata_for_year",
    "RuntimeConfig",
    "RuntimeErrorView",
    "RuntimeFilingIntentView",
    "RuntimeRunCreateRequest",
    "RuntimeRunRecord",
    "RuntimeRunRegistry",
    "RuntimeRunView",
    "RuntimeStage",
    "RuntimeWarning",
    "runtime_config_for_report_synthesis_model",
    "runtime_contract_json_schemas",
    "runtime_run_create_request_json_schema",
    "runtime_run_view_json_schema",
    "select_canonical_source",
    "select_canonical_source_from_classifications",
    "SourceCandidate",
    "SourceConfirmationSlot",
    "SourceConfirmationView",
    "SqliteReportArtifactCacheRepository",
    "assert_public_runtime_payload_safe",
    "validate_company_report_set",
    "validate_filing_intent_error_response",
    "validate_filing_package",
    "validate_final_report_endpoint",
    "validate_runtime_run_create_request",
    "render_final_report_markdown",
    "validate_raw_extraction_artifact",
    "report_memory_cache_compatibility_for_llm_normalizer",
    "map_raw_ocr_artifact_to_extraction_candidates",
    "MAPPER_VERSION",
    "validate_final_report",
    "validate_real_extraction_quality_gate",
    "validate_llm_normalizer_output",
    "validate_report_memory",
    "validate_runtime_run_view",
    "validate_source_document_classification",
    "write_final_report",
]
